server:
  port: 8081


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5332/customer
    username: sun
    password: 1234

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-request-size: 10MB
      enabled: true
      max-file-size: 10MB
      location: C:\\Users\\SUN\\work\\airbnb-react-spring\\ui\\public\\images



#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            clientId:
#            clientSecret:
#
#          google:
#            client-id:
#            client-secret:


airbnb.upload.path: C:\\Users\\SUN\\work\\airbnb-react-spring\\ui\\public\\images