server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5332/customer
    username: sun
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-request-size: 10MB
      enabled: true
      max-file-size: 10MB
      location: C:\\Users\\SUN\\work\\airbnb-react-spring\\ui\\public\\images



  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 7f1381291e01e550af47
            clientSecret: 0ddafd23c14c4b73b91ea82fd15f06ab4d6a977c

          google:
            client-id: google-client-id
            client-secret: google-client-secret


airbnb.upload.path: C:\\Users\\SUN\\work\\airbnb-react-spring\\ui\\public\\images